# Generated by Django 5.2.6 on 2025-09-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
